import type { Metadata } from "next";
import { ThemeModeScript, ThemeProvider } from "flowbite-react";
import Navigation from '../app/components/Navigation';
import theme from '../app/flowbite-theme';
import { ThemeInit } from "../../.flowbite-react/init";
import { Roboto } from "next/font/google";
import { clsx } from 'clsx';
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin", 'latin-ext']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className={clsx(roboto.className, 'flex h-full flex-col antialiased bg-gray-100 dark:bg-gray-800')}>
        <ThemeProvider theme={theme}>
          <ThemeInit />
          <Navigation />
          {children}
        </ThemeProvider>
      </body>
    </html>

  );
}
